// <auto-generated />
using CommanderGQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommanderGQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220125233414_DeleteFlightNoAddStarShipId")]
    partial class DeleteFlightNoAddStarShipId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommanderGQL.Models.Crew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Persson")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StarShipFlightId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StarShipFlightId");

                    b.HasIndex("Persson", "StarShipFlightId")
                        .IsUnique();

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("CommanderGQL.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Persson")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StarShipFlightId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StarShipFlightId");

                    b.HasIndex("Persson", "StarShipFlightId")
                        .IsUnique();

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("CommanderGQL.Models.StarShipFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("StarshipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StarShipFlights");
                });

            modelBuilder.Entity("CommanderGQL.Models.Crew", b =>
                {
                    b.HasOne("CommanderGQL.Models.StarShipFlight", "StarShipFlight")
                        .WithMany("Crews")
                        .HasForeignKey("StarShipFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StarShipFlight");
                });

            modelBuilder.Entity("CommanderGQL.Models.Passenger", b =>
                {
                    b.HasOne("CommanderGQL.Models.StarShipFlight", "StarShipFlight")
                        .WithMany("Passengers")
                        .HasForeignKey("StarShipFlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StarShipFlight");
                });

            modelBuilder.Entity("CommanderGQL.Models.StarShipFlight", b =>
                {
                    b.Navigation("Crews");

                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
